export const Products = [{
        id: 1,
        img: "/images/chairs/chair11.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "chair",
        title: "Chair 11",
    },
    {
        id: 2,
        img: "/images/sofa/sofa1.jpg",
        desc: "products desc is here....",
        price: 3000,
        category: "sofa",
        title: "Sofa 1",
    },
    {
        id: 3,
        img: "/images/bed/bed1.jpg",
        desc: "products desc is here....",
        price: 4000,
        category: "bed",
        title: "Bed 1",
    },
    {
        id: 4,
        img: "/images/tables/table1.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "dinning",
        title: "Dinning Table 1",
    },
    {
        id: 5,
        img: "/images/sofa/sofa2.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "sofa",
        title: "Sofa 2",
    },
    {
        id: 6,
        img: "/images/bed/bed2.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "bed",
        title: "Bed 2",
    },
    {
        id: 7,
        img: "/images/tables/table2.jpg",
        desc: "products desc is here....",
        price: 12000,
        category: "dinning",
        title: "Dinning Table 2",
    },
    {
        id: 8,
        img: "/images/chairs/chair3.jpg",
        desc: "products desc is here....",
        price: 1000,
        category: "chair",
        title: "Chair 3",
    },
    {
        id: 9,
        img: "/images/sofa/sofa3.jpg",
        desc: "products desc is here....",
        price: 12000,
        category: "sofa",
        title: "Sofa 3",
    },
    {
        id: 10,
        img: "/images/chairs/chair4.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "chair",
        title: "Chair 4",
    },
    {
        id: 11,
        img: "/images/bed/bed3.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "bed",
        title: "Bed 3",
    },
    {
        id: 12,
        img: "/images/tables/table3.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "dinning",
        title: "Dinning Table 3",
    },
    {
        id: 13,
        img: "/images/chairs/chair5.jpg",
        desc: "products desc is here....",
        price: 2000,
        title: "Chiar 5",
    },
    {
        id: 14,
        img: "/images/sofa/sofa4.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "sofa",
        title: "Sofa Set 4",
    },
    {
        id: 15,
        img: "/images/bed/bed4.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "bed",
        title: "Bed 4",
    },
    {
        id: 16,
        img: "/images/tables/table4.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "dinning",
        title: "Dinning Table 4",
    },
    {
        id: 17,
        img: "/images/chairs/chair6.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "chair",
        title: "Chair 6",
    },
    {
        id: 18,
        img: "/images/sofa/sofa5.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "sofa",
        title: "Sofa 5",
    },
    {
        id: 19,
        img: "/images/bed/bed5.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "bed",
        title: "Bed 5",
    },
    {
        id: 20,
        img: "/images/tables/table5.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "dinning",
        title: "Dinning Table 5",
    },
    {
        id: 21,
        img: "/images/chairs/chair7.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "chair",
        title: "Chair 7",
    },
    {
        id: 22,
        img: "/images/sofa/sofa6.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "sofa",
        title: "Sofa Set 6",
    },
    {
        id: 23,
        img: "/images/bed/bed6.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "bed",
        title: "Bed 6",
    },
    {
        id: 24,
        img: "/images/tables/table6.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "dinning",
        title: "Dinning Table 6",
    },
    {
        id: 25,
        img: "/images/chairs/chair8.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "chair",
        title: "Chair 8",
    },
    {
        id: 26,
        img: "/images/sofa/sofa8.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "sofa",
        title: "Sofa Set 8",
    },
    {
        id: 27,
        img: "/images/chairs/chair9.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "chair",
        title: "Chair 9",
    },
    {
        id: 28,
        img: "/images/bed/bed8.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "bed",
        title: "Bed 8",
    },
    {
        id: 29,
        img: "/images/tables/table7.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "dinning",
        title: "Dinning Table 7",
    },
    {
        id: 30,
        img: "/images/sofa/sofa9.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "sofa",
        title: "Sofa 9",
    },
    {
        id: 31,
        img: "/images/bed/bed9.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "bed",
        title: "Bed 9",
    },
    {
        id: 32,
        img: "/images/tables/table8.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "dinning",
        title: "Dinning Table8",
    },
    {
        id: 33,
        img: "/images/chairs/chair10.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "chair",
        title: "Chair 10",
    },
    {
        id: 34,
        img: "/images/sofa/sofa10.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "sofa",
        title: "Sofa Set10",
    },
    {
        id: 35,
        img: "/images/chairs/chair13.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "chair",
        title: "Chair 13",
    },
    {
        id: 36,
        img: "/images/bed/bed10.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "bed",
        title: "Bed 10",
    },
    {
        id: 37,
        img: "/images/tables/table9.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "dinning",
        title: "Dinning Table9",
    },
    {
        id: 38,
        img: "/images/chairs/chair14.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "chair",
        title: "Chair 14",
    },
    {
        id: 39,
        img: "/images/tables/table10.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "dinning",
        title: "Dinning Table10",
    },
];

export const categories = [{
        id: 1,
        img: "/images/bed/bed15.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "bed",
        title: "I-Phone 11",
    },
    {
        id: 2,
        img: "/images/sofa/sofa15.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "sofa",
        title: "I-Phone 11",
    },
    {
        id: 3,
        img: "/images/tables/table15.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "dinning",
        title: "I-Phone 11",
    },
    {
        id: 4,
        img: "/images/chairs/chair15.jpg",
        desc: "products desc is here....",
        price: 2000,
        category: "chair",
        title: "I-Phone 11",
    },
];

export const CommingSoon = [{
        id: 1,
        img: "/images/bed/bed13.jpg",
        desc: "products desc is here....",
        price: 20000,
        title: "Bed",
    },

    {
        id: 2,
        img: "/images/sofa/sofa13.jpg",
        desc: "products desc is here....",
        price: 13599,
        title: "Sofa",
    },
    {
        id: 3,
        img: "/images/tables/table13.jpg",
        desc: "products desc is here....",
        price: 3600,
        title: "Dinning Table",
    },
    {
        id: 4,
        img: "/images/chairs/chair13.jpg",
        desc: "products desc is here....",
        price: 500,
        title: "Chair",
    },
];

export const FlashDeals = [{
        id: 100,
        img: "/images/bed/bed12.jpg",
        desc: "products desc is here....",
        price: 15000,
        off: 47,
        title: "Bed",
    },

    {
        id: 101,
        img: "/images/sofa/sofa12.jpg",
        desc: "products desc is here....",
        price: 11500,
        off: 69,
        title: "sofa",
    },
    {
        id: 102,
        img: "/images/tables/table12.jpg",
        desc: "products desc is here....",
        price: 7700,
        off: 72,
        title: "Dinning Table",
    },
    {
        id: 103,
        img: "/images/chairs/chair20.jpg",
        desc: "products desc is here....",
        price: 1500,
        off: 70,
        title: "Chair",
    },
    {
        id: 104,
        img: "/images/bed/bed11.jpg",
        desc: "products desc is here....",
        price: 9500,
        off: 50,
        title: "Bed",
    },
    {
        id: 105,
        img: "/images/sofa/sofa11.jpg",
        desc: "products desc is here....",
        price: 6300,
        off: 35,
        title: "Sofa",
    },
];